apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ep-deployment-hpa
  namespace: splunk-edge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ep-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
