#!/usr/bin/env bash
# Write helm/edge-processor/values-install.yaml from parsed install-script variables.
# Requires: parse_install_script already run (PACKAGE_URL, GROUP_ID, etc.)

set -euo pipefail

write_helm_values_from_install_script() {
  local out_file="${1:?output file required}"

  : "${DMX_HOST:?DMX_HOST}"
  : "${GROUP_ID:?GROUP_ID}"
  : "${PACKAGE_URL:?PACKAGE_URL}"
  : "${SPLUNK_EDGE_PACKAGE_CHECKSUM:?SPLUNK_EDGE_PACKAGE_CHECKSUM}"

  : "${DMX_TOKEN:?DMX_TOKEN}"

  local dmx_env="${DMX_ENV:-production}"
  local dmx_insecure="${DMX_INSECURE:-false}"
  local mgmt_proxy="${MGMT_PROXY_ENABLED:-true}"
  local group_key="${GROUP_KEY:-EP_INSTANCE}"
  local image_repo="" image_tag=""
  if [[ -n "${IMAGE_OVERRIDE:-}" ]]; then
    image_repo="${IMAGE_OVERRIDE%%:*}"
    image_tag="${IMAGE_OVERRIDE##*:}"
    if [[ "${image_repo}" == "${IMAGE_OVERRIDE}" ]]; then
      image_tag="latest"
    fi
  fi

  cat > "${out_file}" <<EOF
# Generated by setup-from-install-script.sh — do not commit (gitignored)
splunk:
  dmxHost: "${DMX_HOST}"
  dmxEnv: "${DMX_ENV}"
  groupId: "${GROUP_ID}"
  groupConfigMapKey: "${GROUP_KEY}"
  packageUrl: "${PACKAGE_URL}"
  packageChecksum: "${SPLUNK_EDGE_PACKAGE_CHECKSUM}"
  dmxInsecure: ${dmx_insecure}
  mgmtProxyEnabled: ${mgmt_proxy}

secret:
  create: true
  provisioningToken: "${DMX_TOKEN}"
EOF

  if [[ -n "${image_repo}" ]]; then
    cat >> "${out_file}" <<EOF

image:
  repository: ${image_repo}
  tag: ${image_tag}
EOF
  fi

  echo "Wrote ${out_file}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  # shellcheck source=lib/parse-install-script.sh
  source "${SCRIPT_DIR}/lib/parse-install-script.sh"
  if [[ $# -lt 2 ]]; then
    echo "Usage: $0 <install-script.txt> <output-yaml>" >&2
    exit 1
  fi
  GROUP_KEY="${GROUP_KEY:-EP_INSTANCE}"
  parse_install_script "$1"
  validate_parsed_install_script
  write_helm_values_from_install_script "$2"
fi
