#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CHART_DIR="${ROOT_DIR}/helm/edge-processor"
VALUES_NSG="${CHART_DIR}/values-nsg.yaml"

# shellcheck source=lib/load-env.sh
source "${SCRIPT_DIR}/lib/load-env.sh"
# shellcheck source=lib/nsg-allowed-sources.sh
source "${SCRIPT_DIR}/lib/nsg-allowed-sources.sh"
load_ep_env "${ROOT_DIR}"

RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:?set AZURE_RESOURCE_GROUP in .env}"
NSG_NAME="${NSG_NAME:-ep-edge-nsg}"
HEC_PORT="${NSG_HEC_PORT:-8088}"
S2S_PORT="${NSG_S2S_PORT:-9997}"

usage() {
  cat <<EOF
Usage: $0

Apply inbound allow rules on ${NSG_NAME:-ep-edge-nsg} for HEC (${NSG_HEC_PORT:-8088}) and S2S (${NSG_S2S_PORT:-9997}),
and write helm/edge-processor/values-nsg.yaml for Azure Load Balancer source filtering.

Sources are read from NSG_ALLOWED_SOURCES_FILE (default: config/nsg-allowed-sources.conf).
If that file is missing or empty, NSG_ALLOWED_SOURCES_DEFAULT is used (default: 0.0.0.0/0).

Safe to re-run when on-prem egress IPs change.
EOF
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  usage
  exit 0
fi

if ! command -v az >/dev/null 2>&1; then
  echo "ERROR: az CLI is not installed." >&2
  exit 1
fi

if ! nsg_load_allowed_sources "${ROOT_DIR}"; then
  exit 1
fi

if ! az network nsg show --resource-group "${RESOURCE_GROUP}" --name "${NSG_NAME}" >/dev/null 2>&1; then
  echo "ERROR: NSG ${NSG_NAME} not found in ${RESOURCE_GROUP}. Run ./scripts/setup-network.sh first." >&2
  exit 1
fi

apply_rule() {
  local rule_name="$1"
  local priority="$2"
  local port="$3"

  if az network nsg rule show \
    --resource-group "${RESOURCE_GROUP}" \
    --nsg-name "${NSG_NAME}" \
    --name "${rule_name}" >/dev/null 2>&1; then
    echo "  Updating NSG rule ${rule_name} (TCP ${port})"
    az network nsg rule update \
      --resource-group "${RESOURCE_GROUP}" \
      --nsg-name "${NSG_NAME}" \
      --name "${rule_name}" \
      --priority "${priority}" \
      --direction Inbound \
      --access Allow \
      --protocol Tcp \
      --source-address-prefixes "${NSG_ALLOWED_SOURCES[@]}" \
      --source-port-ranges "*" \
      --destination-address-prefix "*" \
      --destination-port-ranges "${port}" \
      -o none
  else
    echo "  Creating NSG rule ${rule_name} (TCP ${port})"
    az network nsg rule create \
      --resource-group "${RESOURCE_GROUP}" \
      --nsg-name "${NSG_NAME}" \
      --name "${rule_name}" \
      --priority "${priority}" \
      --direction Inbound \
      --access Allow \
      --protocol Tcp \
      --source-address-prefixes "${NSG_ALLOWED_SOURCES[@]}" \
      --source-port-ranges "*" \
      --destination-address-prefix "*" \
      --destination-port-ranges "${port}" \
      -o none
  fi
}

echo "Applying allow rules on NSG ${NSG_NAME} (${#NSG_ALLOWED_SOURCES[@]} source(s))"
apply_rule "ep-allow-hec-onprem" 100 "${HEC_PORT}"
apply_rule "ep-allow-s2s-onprem" 101 "${S2S_PORT}"

ALLOW_CSV="$(nsg_allowed_sources_csv)"
cat > "${VALUES_NSG}" <<EOF
# Generated by scripts/apply-nsg-rules.sh — do not edit by hand.
service:
  annotations:
    service.beta.kubernetes.io/azure-allowed-ip-ranges: "${ALLOW_CSV}"
EOF

echo "  Wrote ${VALUES_NSG} (Azure LB allow-list annotation)"
echo "Done."
