apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.headlessService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edge-processor.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "edge-processor.selectorLabels" . | nindent 4 }}
  ports:
    - name: s2s
      protocol: TCP
      port: {{ .Values.service.ports.s2s }}
      targetPort: {{ .Values.service.ports.s2s }}
    - name: hec
      protocol: TCP
      port: {{ .Values.service.ports.hec }}
      targetPort: {{ .Values.service.ports.hec }}
